spring:
  application:
    name: LMS-GETWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: LIBRARYMANAGEMENT
          uri: lb://LIBRARYMANAGEMENT
          predicates:
            - Path=/catalogue/**, /acquisition/**, /api/auth/**, /circulation/**, /members/**, /review/**

server:
  port: 8086

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/